global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'avalanchego-validator'
    metrics_path: /ext/metrics
    static_configs:
      - targets:
          - '18.183.88.206:9652'
          - '13.113.48.18:9652'
          - '35.78.177.10:9652'
