global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'avalanchego'
    metrics_path: /ext/metrics
    static_configs:
      - targets:
          - '13.231.135.36:9650'
          - '13.231.132.89:9650'
          - '18.183.163.177:9650'
